version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start server and tests
          command:
            npm install
            ng serve
            ng e2e
            npm run e2eReport
