version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start server and tests
          command:
            npm install
            ng serve
            ng e2e
      - store_test_results:
            path: allure-results
      - run:
          name: Create report
          command:
            npm run e2eReport
